const { Schema, model } = require('mongoose');
const { persianDate } = require('./../libs/jalali')

const positionSchema = new Schema({
    user_id            : String,
    symbol             : String,
    size               : String,
    side               : String,
    position_value     : String,
    entry_price        : String,
    liq_price          : String,
    bust_price         : String,
    leverage           : String,
    order_margin       : String,
    position_margin    : String,
    occ_closing_fee    : String,
    take_profit        : String,
    tp_trigger_by      : String,
    stop_loss          : String,
    sl_trigger_by      : String,
    trailing_stop      : String,
    realised_pnl       : String,
    auto_add_margin    : String,
    cum_realised_pnl   : String,
    position_status    : String,
    position_id        : String,
    position_seq       : String,
    adl_rank_indicator : String,
    free_qty           : String,
    tp_sl_mode         : String,
    risk_id            : String,
    isolated           : String,
    mode               : String,
    position_idx       : String,
    timestamp          : {type: String, default: Date.now()},
    second             : { type: String, default: persianDate().second },
    minute             : { type: String, default: persianDate().minute },
    hour               : { type: String, default: persianDate().hour },
    day                : { type: String, default: persianDate().day },
    month              : { type: String, default: persianDate().month },
    year               : { type: String, default: persianDate().year },
})
module.exports = model('positions', positionSchema)